version: '2'

services:
    web:
        build: node-server/
        volumes:
            - chat_logs:/var/log/chat/
        networks:
            - backend

    proxy:
        build: chat-proxy/
        ports:
            - 80:80
        depends_on:
            - "web"
        volumes:
            - nginx_logs:/var/log/nginx/
        networks:
            - backend

    filebeat:
        build: filebeat/
        volumes:
            - chat_logs:/var/log/chat/
            - nginx_logs:/var/log/nginx/
            - filebeat_logs:/var/log/mybeat/
        networks:
            - backend
        environment:
            LOGSTASH_HOST:

volumes:
    chat_logs:
    nginx_logs:
    filebeat_logs:

networks:
    backend:
