version: '2'

services:
    web:
        build: node-server/
        volumes_from:
            - filebeat
        networks:
            - backend

    proxy:
        build: chat-proxy/
        ports:
            - 80:80
        depends_on:
            - "web"
        volumes_from:
            - filebeat
        networks:
            - backend

    filebeat:
        build: filebeat/
        volumes:
            - /var/log/chat/
            - /var/log/nginx/
            - /var/log/mybeat/
        networks:
            - backend
        environment:
            LOGSTASH_HOST:

networks:
    backend:
